
############  input_number:  #####################  
input_number:
  frontdoor_accesscount_3:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############  
input_datetime:
  end_date_3:
    name: 'End'
    has_time: false
    has_date: true
  start_date_3:
    name: 'Start'
    has_time: false
    has_date: true


  sunstart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  sunend_date_3:
    name: 'End'
    has_time: true
    has_date: false

  monstart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  monend_date_3:
    name: 'End'
    has_time: true
    has_date: false

  tuestart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  tueend_date_3:
    name: 'End'
    has_time: true
    has_date: false

  wedstart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  wedend_date_3:
    name: 'End'
    has_time: true
    has_date: false

  thustart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  thuend_date_3:
    name: 'End'
    has_time: true
    has_date: false

  fristart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  friend_date_3:
    name: 'End'
    has_time: true
    has_date: false

  satstart_date_3:
    name: 'Start'
    has_time: true
    has_date: false
  satend_date_3:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  frontdoor_name_3:
    name: 'Name'
  frontdoor_pin_3:
    name: 'PIN'

#################  input_boolean: ################  
input_boolean:
  frontdoor_notify_3:
    name: 'Notifications'
  frontdoor_daterange_3:
    name: 'Use Date Range'
  frontdoor_smtwtfs_3:
    name: 'Use SMTWTFS'
  frontdoor_enabled_3:
    name: 'Enabled'
  frontdoor_accesslimit_3:
    name: 'Limit Access Count'
    initial: off

  sun_3:
    name: 'Sunday'
    initial: on

  mon_3:
    name: 'Monday'
    initial: on

  tue_3:
    name: 'Tuesday'
    initial: on

  wed_3:
    name: 'Wednesday'
    initial: on

  thu_3:
    name: 'Thursday'
    initial: on

  fri_3:
    name: 'Friday'
    initial: on

  sat_3:
    name: 'Saturday'
    initial: on

################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    frontdoor_enabled_3:
      value_template: "{{ is_state('input_boolean.frontdoor_enabled_3', 'on') }}"

    frontdoor_daterange_3:
      value_template: "{{ (is_state('input_boolean.frontdoor_daterange_3', 'off') or ((states.input_datetime.start_date_3.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_3.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

    sun_3:
      value_template: "{{ ((is_state('input_boolean.sun_3', 'on'))) and (now().strftime('%A') == 'Sunday') and ((states.input_datetime.sunstart_date_3.state  == states.input_datetime.sunend_date_3.state) or ((states.input_datetime.sunstart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.sunend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    mon_3:
      value_template: "{{ ((is_state('input_boolean.mon_3', 'on'))) and (now().strftime('%A') == 'Monday') and ((states.input_datetime.monstart_date_3.state  == states.input_datetime.monend_date_3.state) or ((states.input_datetime.monstart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.monend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    tue_3:
      value_template: "{{ ((is_state('input_boolean.tue_3', 'on'))) and (now().strftime('%A') == 'Tuesday') and ((states.input_datetime.tuestart_date_3.state  == states.input_datetime.tueend_date_3.state) or ((states.input_datetime.tuestart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.tueend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    wed_3:
      value_template: "{{ ((is_state('input_boolean.wed_3', 'on'))) and (now().strftime('%A') == 'Wednesday') and ((states.input_datetime.wedstart_date_3.state  == states.input_datetime.wedend_date_3.state) or ((states.input_datetime.wedstart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.wedend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    thu_3:
      value_template: "{{ ((is_state('input_boolean.thu_3', 'on'))) and (now().strftime('%A') == 'Thursday') and ((states.input_datetime.thustart_date_3.state  == states.input_datetime.thuend_date_3.state) or ((states.input_datetime.thustart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.thuend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    fri_3:
      value_template: "{{ ((is_state('input_boolean.fri_3', 'on'))) and (now().strftime('%A') == 'Friday') and ((states.input_datetime.fristart_date_3.state  == states.input_datetime.friend_date_3.state) or ((states.input_datetime.fristart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.friend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    sat_3:
      value_template: "{{ ((is_state('input_boolean.sat_3', 'on'))) and (now().strftime('%A') == 'Saturday') and ((states.input_datetime.satstart_date_3.state  == states.input_datetime.satend_date_3.state) or ((states.input_datetime.satstart_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.satend_date_3.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"


    smtwtfs_3:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.sun_3', 'on')  or  
            is_state('binary_sensor.mon_3', 'on')  or  
            is_state('binary_sensor.tue_3', 'on')  or  
            is_state('binary_sensor.wed_3', 'on')  or  
            is_state('binary_sensor.thu_3', 'on')  or  
            is_state('binary_sensor.fri_3', 'on')  or  
            is_state('binary_sensor.sat_3', 'on')   
         }}

    
    access_count_3:
      friendly_name: "Access Count"
      value_template: >-
         {{
            (is_state('input_boolean.frontdoor_accesslimit_3', 'off'))  or  
            (states.input_number.frontdoor_accesscount_3.state | int > 0)
         }}


    frontdoor_active_3:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.frontdoor_enabled_3', 'on')  and  
            is_state('binary_sensor.access_count_3', 'on')  and  
            is_state('binary_sensor.frontdoor_daterange_3', 'on') and
            is_state('binary_sensor.smtwtfs_3', 'on')  
         }}
      device_class: connectivity


###################  sensor:  ####################  

