############  input_number:  #####################
input_number:
  accesscount_LOCKNAME_TEMPLATENUM:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############
input_datetime:
  end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: false
    has_date: true
  start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: false
    has_date: true

  sun_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  sun_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

  mon_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  mon_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

  tue_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  tue_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

  wed_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  wed_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

  thu_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  thu_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

  fri_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  fri_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

  sat_start_date_LOCKNAME_TEMPLATENUM:
    name: "Start"
    has_time: true
    has_date: false
  sat_end_date_LOCKNAME_TEMPLATENUM:
    name: "End"
    has_time: true
    has_date: false

####################  input_text:  ###############
input_text:
  LOCKNAME_name_TEMPLATENUM:
    name: "Name"

  LOCKNAME_pin_TEMPLATENUM:
    name: "PIN"

#################  input_boolean: ################
input_boolean:
  notify_LOCKNAME_TEMPLATENUM:
    name: "Notifications"
  daterange_LOCKNAME_TEMPLATENUM:
    name: "Use Date Range"
  smtwtfs_LOCKNAME_TEMPLATENUM:
    name: "Use SMTWTFS"
  enabled_LOCKNAME_TEMPLATENUM:
    name: "Enabled"
  accesslimit_LOCKNAME_TEMPLATENUM:
    name: "Limit Access Count"
    initial: off
  reset_codeslot_LOCKNAME_TEMPLATENUM:
    name: "Reset Code Slot"
    initial: off

  sun_LOCKNAME_TEMPLATENUM:
    name: "Sunday"
    initial: on

  mon_LOCKNAME_TEMPLATENUM:
    name: "Monday"
    initial: on

  tue_LOCKNAME_TEMPLATENUM:
    name: "Tuesday"
    initial: on

  wed_LOCKNAME_TEMPLATENUM:
    name: "Wednesday"
    initial: on

  thu_LOCKNAME_TEMPLATENUM:
    name: "Thursday"
    initial: on

  fri_LOCKNAME_TEMPLATENUM:
    name: "Friday"
    initial: on

  sat_LOCKNAME_TEMPLATENUM:
    name: "Saturday"
    initial: on

  sun_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

  mon_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

  tue_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

  wed_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

  thu_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

  fri_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

  sat_inc_LOCKNAME_TEMPLATENUM:
    name: "include (on)/exclude (off)"
    initial: on

################  automation: #################
automation:
  - alias: reset_codeslot_LOCKNAME_TEMPLATENUM
    trigger:
      entity_id: input_boolean.reset_codeslot_LOCKNAME_TEMPLATENUM
      platform: state
      to: "on"
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.LOCKNAME_name_TEMPLATENUM
          value: ""
      - service: input_text.set_value
        data_template:
          entity_id: input_text.LOCKNAME_pin_TEMPLATENUM
          value: ""

      - service: input_boolean.turn_off
        entity_id: input_boolean.notify_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_off
        entity_id: input_boolean.enabled_LOCKNAME_TEMPLATENUM

      - service: input_number.set_value
        data_template:
          entity_id: input_number.accesscount_LOCKNAME_TEMPLATENUM
          value: "0"

      - service: input_datetime.set_datetime
        entity_id: input_datetime.sun_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.sun_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.mon_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.mon_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.tue_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.tue_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.wed_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.wed_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.thu_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.thu_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.fri_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.fri_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.sat_start_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}
      - service: input_datetime.set_datetime
        entity_id: input_datetime.sat_end_date_LOCKNAME_TEMPLATENUM
        data_template:
          time: >
            {{  (("00:00")  | timestamp_custom("%H:%M"))  }}

      - service: input_datetime.set_datetime
        entity_id: input_datetime.start_date_LOCKNAME_TEMPLATENUM
        data_template:
          date: >
            {{  (("1980-01-01")  | timestamp_custom("%Y %m %d"))  }}

      - service: input_datetime.set_datetime
        entity_id: input_datetime.end_date_LOCKNAME_TEMPLATENUM
        data_template:
          date: >
            {{  (("1980-01-01")  | timestamp_custom("%Y %m %d"))  }}

      - service: input_boolean.turn_off
        entity_id: input_boolean.daterange_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_off
        entity_id: input_boolean.accesslimit_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_off
        entity_id: input_boolean.reset_codeslot_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.sun_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.mon_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.tue_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.wed_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.thu_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.fri_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.sat_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.sun_inc_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.mon_inc_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.tue_inc_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.wed_inc_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.thu_inc_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.fri_inc_LOCKNAME_TEMPLATENUM

      - service: input_boolean.turn_on
        entity_id: input_boolean.sat_inc_LOCKNAME_TEMPLATENUM

################  binary_sensor: #################
binary_sensor:
  - platform: template
    sensors:
      enabled_LOCKNAME_TEMPLATENUM:
        value_template: "{{ is_state('input_boolean.enabled_LOCKNAME_TEMPLATENUM', 'on') }}"

      daterange_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (is_state('input_boolean.daterange_LOCKNAME_TEMPLATENUM', 'off') or ((states.input_datetime.start_date_LOCKNAME_TEMPLATENUM.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_LOCKNAME_TEMPLATENUM.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

      sun_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.sun_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'sun') and (is_state('input_boolean.sun_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.sun_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.sun_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.sun_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.sun_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      mon_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.mon_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'mon') and (is_state('input_boolean.mon_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.mon_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.mon_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.mon_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.mon_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      tue_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.tue_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'tue') and (is_state('input_boolean.tue_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.tue_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.tue_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.tue_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.tue_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      wed_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.wed_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'wed') and (is_state('input_boolean.wed_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.wed_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.wed_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.wed_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.wed_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      thu_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.thu_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'thu') and (is_state('input_boolean.thu_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.thu_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.thu_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.thu_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.thu_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      fri_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.fri_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'fri') and (is_state('input_boolean.fri_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.fri_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.fri_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.fri_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.fri_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      sat_LOCKNAME_TEMPLATENUM:
        value_template: "{{ (( is_state('input_boolean.sat_LOCKNAME_TEMPLATENUM', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%a') | lower == 'sat') and (is_state('input_boolean.sat_inc_LOCKNAME_TEMPLATENUM', 'on')) == ((states.input_datetime.sat_start_date_LOCKNAME_TEMPLATENUM.state == states.input_datetime.sat_end_date_LOCKNAME_TEMPLATENUM.state) or ((states('sensor.time') >= states('input_datetime.sat_start_date_LOCKNAME_TEMPLATENUM')[0:5]) and (states('sensor.time') <= states('input_datetime.sat_end_date_LOCKNAME_TEMPLATENUM')[0:5])) )}}"

      smtwtfs_LOCKNAME_TEMPLATENUM:
        friendly_name: "Status"
        value_template: >-
          {{
             is_state('binary_sensor.sun_LOCKNAME_TEMPLATENUM', 'on')  or  
             is_state('binary_sensor.mon_LOCKNAME_TEMPLATENUM', 'on')  or  
             is_state('binary_sensor.tue_LOCKNAME_TEMPLATENUM', 'on')  or  
             is_state('binary_sensor.wed_LOCKNAME_TEMPLATENUM', 'on')  or  
             is_state('binary_sensor.thu_LOCKNAME_TEMPLATENUM', 'on')  or  
             is_state('binary_sensor.fri_LOCKNAME_TEMPLATENUM', 'on')  or  
             is_state('binary_sensor.sat_LOCKNAME_TEMPLATENUM', 'on')   
          }}

      access_count_LOCKNAME_TEMPLATENUM:
        friendly_name: "Access Count"
        value_template: >-
          {{
             (is_state('input_boolean.accesslimit_LOCKNAME_TEMPLATENUM', 'off'))  or  
             (states.input_number.accesscount_LOCKNAME_TEMPLATENUM.state | int > 0)
          }}

      active_LOCKNAME_TEMPLATENUM:
        friendly_name: "Status"
        value_template: >-
          {{
             is_state('binary_sensor.enabled_LOCKNAME_TEMPLATENUM', 'on')  and  
             is_state('binary_sensor.access_count_LOCKNAME_TEMPLATENUM', 'on')  and  
             is_state('binary_sensor.daterange_LOCKNAME_TEMPLATENUM', 'on') and
             is_state('binary_sensor.smtwtfs_LOCKNAME_TEMPLATENUM', 'on')  
          }}
        device_class: connectivity
###################  sensor:  ####################
